FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY vite.config.js .
COPY tailwind.config.js .
COPY postcss.config.js .
COPY index.html .
COPY src ./src
COPY public ./public

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]