server:
  port: 8080
  env: development

corteza:
  client_id: "the-auth-client-id"
  client_secret: "the-actual-secret-from-corteza-admin"
  auth_base_url: "http://corteza-server/auth"
  redirect_uri: "http://localhost:5173/callback"
